steps:
- label: ":docker: Build and publish"
  command: 'docker build -t ${REPOSITORY_URI}:${BUILDKITE_BUILD_ID} .'
  plugins:
    healthforge/docker-tags:
      registry: '${REPOSITORY_URI}'
      tag: '${BUILDKITE_BUILD_ID}'
