steps:
- label: ":docker: Build and publish"
  command:
  - docker build -t healthforge/git .
  - docker push healthforge/git
  plugins:
  - docker-login#v2.0.1:
      server: docker.io
      username: hfminion
      password-env: DOCKER_HUB_PASSWORD
  agents:
    queue: hf-dev
